//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMap.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the clock&apos;s {0}. min. points to moon, hour 12 points to north|These are clock wheel&apos;s hours and minutes.
        /// </summary>
        internal static string msgClockMoonNoonDirection {
            get {
                return ResourceManager.GetString("msgClockMoonNoonDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the clock&apos;s {0}. min. points to object, hour 12 points to north|These are clock wheel&apos;s hours and minutes.
        /// </summary>
        internal static string msgClockObjectNoonDirection {
            get {
                return ResourceManager.GetString("msgClockObjectNoonDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the clock&apos;s {0}. min. points to sun, hour 12 points to north|These are clock wheel&apos;s hours and minutes.
        /// </summary>
        internal static string msgClockSunNoonDirection {
            get {
                return ResourceManager.GetString("msgClockSunNoonDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass   [{0}]|The window title with a clock on it.
        /// </summary>
        internal static string msgCompass {
            get {
                return ResourceManager.GetString("msgCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long name|A name of the constellation.
        /// </summary>
        internal static string msgConstellationLongName {
            get {
                return ResourceManager.GetString("msgConstellationLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name|An abbreviation of the constellation name.
        /// </summary>
        internal static string msgConstellationShortName {
            get {
                return ResourceManager.GetString("msgConstellationShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time: {0}|A formatted date and time.
        /// </summary>
        internal static string msgDateAndTime {
            get {
                return ResourceManager.GetString("msgDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day|As in day of time.
        /// </summary>
        internal static string msgDay {
            get {
                return ResourceManager.GetString("msgDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days|In a combo box selection list.
        /// </summary>
        internal static string msgDays {
            get {
                return ResourceManager.GetString("msgDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon&apos;s direction line color|The color of moon&apos;s direction line in the compass..
        /// </summary>
        internal static string msgDirectionLineColorMoon {
            get {
                return ResourceManager.GetString("msgDirectionLineColorMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom objects&apos;s direction line color|The color of the custom object&apos;s direction line in the compass..
        /// </summary>
        internal static string msgDirectionLineColorObject {
            get {
                return ResourceManager.GetString("msgDirectionLineColorObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun&apos;s direction line color|The color of sun&apos;s direction line in the compass..
        /// </summary>
        internal static string msgDirectionLineColorSun {
            get {
                return ResourceManager.GetString("msgDirectionLineColorSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width(x), height(y) and distance to sun (z) (km): {0:F1}|A distance to the sun, area width and height.
        /// </summary>
        internal static string msgDistanceFromTheSunXYZkm {
            get {
                return ResourceManager.GetString("msgDistanceFromTheSunXYZkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth and moon|Zoomed to the earth and moon.
        /// </summary>
        internal static string msgEarthAndMoon1x {
            get {
                return ResourceManager.GetString("msgEarthAndMoon1x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth and moon x 2|Zoomed to the earth and moon by 2x.
        /// </summary>
        internal static string msgEarthAndMoon2x {
            get {
                return ResourceManager.GetString("msgEarthAndMoon2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAST|As the east as in compass point.
        /// </summary>
        internal static string msgEast {
            get {
                return ResourceManager.GetString("msgEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east|east as long text.
        /// </summary>
        internal static string msgEastLong {
            get {
                return ResourceManager.GetString("msgEastLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E|East upper case.
        /// </summary>
        internal static string msgEastShortUpper {
            get {
                return ResourceManager.GetString("msgEastShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|As in an error occurred..
        /// </summary>
        internal static string msgErrorDialogCaption {
            get {
                return ResourceManager.GetString("msgErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|A standard caption for an error dialog.
        /// </summary>
        internal static string msgErrorDialogCaptionError {
            get {
                return ResourceManager.GetString("msgErrorDialogCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ra/Dec values (&quot;{0}&quot;).|The values of right ascension / declination are invalid.
        /// </summary>
        internal static string msgErrorInvalidRaDecValues {
            get {
                return ResourceManager.GetString("msgErrorInvalidRaDecValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file|A required file is missing.
        /// </summary>
        internal static string msgFileMissing {
            get {
                return ResourceManager.GetString("msgFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot; {0} &quot; can not be found.{1}Because the file is missing the program might not operate well.|A file is missing and may affect the programs behaviour&quot;.
        /// </summary>
        internal static string msgFileNotFound {
            get {
                return ResourceManager.GetString("msgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from east|As in from the east.
        /// </summary>
        internal static string msgFromEast {
            get {
                return ResourceManager.GetString("msgFromEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From map|As a world map which was used to pick a location (lat/lon).
        /// </summary>
        internal static string msgFromMap {
            get {
                return ResourceManager.GetString("msgFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from north|As in from the north.
        /// </summary>
        internal static string msgFromNorth {
            get {
                return ResourceManager.GetString("msgFromNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from northeast|As in from the northeast.
        /// </summary>
        internal static string msgFromNorthEast {
            get {
                return ResourceManager.GetString("msgFromNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F1} ° from north to clockwise|Degrees from north to clockwise.
        /// </summary>
        internal static string msgFromNorthToClockwise {
            get {
                return ResourceManager.GetString("msgFromNorthToClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from northwest|As in from the northwest.
        /// </summary>
        internal static string msgFromNorthWest {
            get {
                return ResourceManager.GetString("msgFromNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from south|As in from the south.
        /// </summary>
        internal static string msgFromSouth {
            get {
                return ResourceManager.GetString("msgFromSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from southeast|As in from the southeast.
        /// </summary>
        internal static string msgFromSouthEast {
            get {
                return ResourceManager.GetString("msgFromSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from southwest|As in from the southwest.
        /// </summary>
        internal static string msgFromSouthWest {
            get {
                return ResourceManager.GetString("msgFromSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from west|As in from the west.
        /// </summary>
        internal static string msgFromWest {
            get {
                return ResourceManager.GetString("msgFromWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ident           : Identification number;RAh             : RA, hours / B1950;RAm             : RA, minutes / B1950;RAs             : RA, seconds / B1950;DE-             : Declination, sign;DEd             : Declination, degrees / B1950;DEm             : Declination, minutes / B1950;pm              : Total proper motion (arcsec/yr);pmPA            : Direction angle of proper motion;RV              : Radial velocity;Sp              : Spectral type or color class;Vmag            : Apparent magnitude;Mv          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msgGlieseItems {
            get {
                return ResourceManager.GetString("msgGlieseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha;Beta;Gamma;Delta;Epsilon;Zeta;Eta;Theta;Iota;Kappa;Lamda;Mu;Nu;Xi;Omicron;Pi;Rho;Sigma;Tau;Upsilon;Phi;Chi;Psi;Omega|Greek alphabet long names.
        /// </summary>
        internal static string msgGreekAlphaLongNames {
            get {
                return ResourceManager.GetString("msgGreekAlphaLongNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to αβγδεζηθικλμνξοπρςτυφχψω|Greek alphabet lower case.
        /// </summary>
        internal static string msgGreekAlphaLower {
            get {
                return ResourceManager.GetString("msgGreekAlphaLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alp;Bet;Gam;Del;Eps;Zet;Eta;The;Iot;Kap;Lam;Mu;Nu;Xi;Omi;Pi;Rho;Sig;Tau;Ups;Phi;Chi;Psi;Ome|Greek alphabet short names.
        /// </summary>
        internal static string msgGreekAlphaShortNames {
            get {
                return ResourceManager.GetString("msgGreekAlphaShortNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ|Greek alphabet upper case.
        /// </summary>
        internal static string msgGreekAlphaUpper {
            get {
                return ResourceManager.GetString("msgGreekAlphaUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Help file &quot;{0}&quot; can not be found.|The file containing help for the software was not found&quot;.
        /// </summary>
        internal static string msgHelpFileNotFound {
            get {
                return ResourceManager.GetString("msgHelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour|As in hour of time.
        /// </summary>
        internal static string msgHour {
            get {
                return ResourceManager.GetString("msgHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours|In a combo box selection list.
        /// </summary>
        internal static string msgHours {
            get {
                return ResourceManager.GetString("msgHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarID          : Star ID;HD              : Star ID / H. Draper database;HR              : Star ID / Harvard/Yale database;Gliese          : Star ID / Gliese database;BayerFlamsteed  : Bayer / Flamsteed designation;Ra              : Right ascension;Dec             : Declination;ProperName      : Common name;Distance        : Distance (pc);Mag             : Magnitude;AbsMag          : Absolute magnitude;Spectrum        : Spectrum;ColorIndex      : Color index|Items for the HYG v.1.1 ComboBox.
        /// </summary>
        internal static string msgHygItems {
            get {
                return ResourceManager.GetString("msgHygItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner solar system|Zoom to the inner solar system.
        /// </summary>
        internal static string msgInnerSolSys {
            get {
                return ResourceManager.GetString("msgInnerSolSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0:F2} °, Longitude: {1:F2} °|Latitude and longitude in degrees.
        /// </summary>
        internal static string msgLatLon {
            get {
                return ResourceManager.GetString("msgLatLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation|An abbreviation of the letter/character name.
        /// </summary>
        internal static string msgLetterAbbreviation {
            get {
                return ResourceManager.GetString("msgLetterAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name|A name of the letter/character.
        /// </summary>
        internal static string msgLetterName {
            get {
                return ResourceManager.GetString("msgLetterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andromeda;Antlia;Apus;Aquila;Aquarius;Ara;Aries;Auriga;Boötes;Caelum;Camelopardalis;Capricornus;Carina;Cassiopeia;Centaurus;Cepheus;Cetus;Chamaeleon;Circinus;Canis Major;Canis Minor;Cancer;Columba;Coma Berenices;Corona Australis;Corona Borealis;Crater;Crux;Corvus;Canes Venatici;Cygnus;Delphinus;Dorado;Draco;Equuleus;Eridanus;Fornax;Gemini;Grus;Hercules;Horologium;Hydra;Hydrus;Indus;Lacerta;Leo;Lepus;Libra;Leo Minor;Lupus;Lynx;Lyra;Mensa;Microscopium;Monoceros;Musca;Norma;Octans;Ophiuchus;Orion;Pavo;Pegasus; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msgLongConstNames {
            get {
                return ResourceManager.GetString("msgLongConstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower case letter|As in lower case letter/character.
        /// </summary>
        internal static string msgLowerLetter {
            get {
                return ResourceManager.GetString("msgLowerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magl:{0:F1}|Magnitude limit in very short form.
        /// </summary>
        internal static string msgMagnitudeLimit {
            get {
                return ResourceManager.GetString("msgMagnitudeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes|In a combo box selection list.
        /// </summary>
        internal static string msgMinutes {
            get {
                return ResourceManager.GetString("msgMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month|As in month of time.
        /// </summary>
        internal static string msgMonth {
            get {
                return ResourceManager.GetString("msgMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months|In a combo box selection list.
        /// </summary>
        internal static string msgMonths {
            get {
                return ResourceManager.GetString("msgMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon is not visible|Moon is not visible.
        /// </summary>
        internal static string msgMoonNotVisible {
            get {
                return ResourceManager.GetString("msgMoonNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth|The name of the Earth.
        /// </summary>
        internal static string msgNameEarth {
            get {
                return ResourceManager.GetString("msgNameEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupiter|The name of Jupiter.
        /// </summary>
        internal static string msgNameJupiter {
            get {
                return ResourceManager.GetString("msgNameJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars|The name of Mars.
        /// </summary>
        internal static string msgNameMars {
            get {
                return ResourceManager.GetString("msgNameMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury|The name of Mercury.
        /// </summary>
        internal static string msgNameMercury {
            get {
                return ResourceManager.GetString("msgNameMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon|The moon.
        /// </summary>
        internal static string msgNameMoon {
            get {
                return ResourceManager.GetString("msgNameMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon|The name of the Moon.
        /// </summary>
        internal static string msgNameMoon2 {
            get {
                return ResourceManager.GetString("msgNameMoon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neptune|The name of Neptune.
        /// </summary>
        internal static string msgNameNeptune {
            get {
                return ResourceManager.GetString("msgNameNeptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluto|The name of Pluto.
        /// </summary>
        internal static string msgNamePluto {
            get {
                return ResourceManager.GetString("msgNamePluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn|The name of Saturn.
        /// </summary>
        internal static string msgNameSaturn {
            get {
                return ResourceManager.GetString("msgNameSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun|The sun.
        /// </summary>
        internal static string msgNameSun {
            get {
                return ResourceManager.GetString("msgNameSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun|The name of the Sun.
        /// </summary>
        internal static string msgNameSun2 {
            get {
                return ResourceManager.GetString("msgNameSun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus|The name of Uranus.
        /// </summary>
        internal static string msgNameUranus {
            get {
                return ResourceManager.GetString("msgNameUranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus|The name of Venus.
        /// </summary>
        internal static string msgNameVenus {
            get {
                return ResourceManager.GetString("msgNameVenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORTH|As the north as in compass point.
        /// </summary>
        internal static string msgNorth {
            get {
                return ResourceManager.GetString("msgNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast|northeast as long text.
        /// </summary>
        internal static string msgNorthEastLong {
            get {
                return ResourceManager.GetString("msgNorthEastLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE|North-East upper case.
        /// </summary>
        internal static string msgNorthEastShortUpper {
            get {
                return ResourceManager.GetString("msgNorthEastShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north|north as long text.
        /// </summary>
        internal static string msgNorthLong {
            get {
                return ResourceManager.GetString("msgNorthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N|North upper case.
        /// </summary>
        internal static string msgNorthShortUpper {
            get {
                return ResourceManager.GetString("msgNorthShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast|northwest as long text.
        /// </summary>
        internal static string msgNorthWestLong {
            get {
                return ResourceManager.GetString("msgNorthWestLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW|North-West upper case.
        /// </summary>
        internal static string msgNorthWestShortUpper {
            get {
                return ResourceManager.GetString("msgNorthWestShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declination|As in declination.
        /// </summary>
        internal static string msgObjectDeclination {
            get {
                return ResourceManager.GetString("msgObjectDeclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name|A string referring to a name word of the object..
        /// </summary>
        internal static string msgObjectName {
            get {
                return ResourceManager.GetString("msgObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not visible|The object is not visible.
        /// </summary>
        internal static string msgObjectNotVisible {
            get {
                return ResourceManager.GetString("msgObjectNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA|Right ascension.
        /// </summary>
        internal static string msgObjectRA {
            get {
                return ResourceManager.GetString("msgObjectRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other object|As in the third object after the sun and the moon for the compass..
        /// </summary>
        internal static string msgOtherObject {
            get {
                return ResourceManager.GetString("msgOtherObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of the other object couldn&apos;t be saved.|The object info save failed..
        /// </summary>
        internal static string msgOtherObjectsInfoCouldNotBeSavedError {
            get {
                return ResourceManager.GetString("msgOtherObjectsInfoCouldNotBeSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon&apos;s precise point of the compass (±1°)|precise point N, S, E, W, NS, ES, NW, NE.
        /// </summary>
        internal static string msgPrecisePointOfTheCompassMoon {
            get {
                return ResourceManager.GetString("msgPrecisePointOfTheCompassMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise point of the compass (±1°)|precise point N, S, E, W, NS, ES, NW, NE.
        /// </summary>
        internal static string msgPrecisePointOfTheCompassObject {
            get {
                return ResourceManager.GetString("msgPrecisePointOfTheCompassObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun&apos;s precise point of the compass (±1°)|precise point N, S, E, W, NS, ES, NW, NE.
        /// </summary>
        internal static string msgPrecisePointOfTheCompassSun {
            get {
                return ResourceManager.GetString("msgPrecisePointOfTheCompassSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds|In a combo box selection list.
        /// </summary>
        internal static string msgSeconds {
            get {
                return ResourceManager.GetString("msgSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your location [{0}]|As in the caption of the window and the location with latitude and longitude.
        /// </summary>
        internal static string msgSelectLocation {
            get {
                return ResourceManager.GetString("msgSelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And;Ant;Aps;Aql;Aqr;Ara;Ari;Aur;Boo;Cae;Cam;Cap;Car;Cas;Cen;Cep;Cet;Cha;Cir;CMa;CMi;Cnc;Col;Com;CrA;CrB;Crt;Cru;Crv;CVn;Cyg;Del;Dor;Dra;Equ;Eri;For;Gem;Gru;Her;Hor;Hya;Hyi;Ind;Lac;Leo;Lep;Lib;LMi;Lup;Lyn;Lyr;Men;Mic;Mon;Mus;Nor;Oct;Oph;Ori;Pav;Peg;Per;Phe;Pic;PsA;Psc;Pup;Pyx;Ret;Scl;Sco;Sct;SeC;Ser;Sex;Sge;Sgr;Tau;Tel;TrA;Tri;Tuc;UMa;UMi;Vel;Vir;Vol;Vul|Short constellation names.
        /// </summary>
        internal static string msgShortConstNames {
            get {
                return ResourceManager.GetString("msgShortConstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar system | Zoom: {0:F0} | X: {1:F1}°,Y: {2:F1}°,Z: {3:F1}° | Ratio: {4:F1}:{5:F1} |As in the caption of the solar system window.
        /// </summary>
        internal static string msgSolarSystemCaption {
            get {
                return ResourceManager.GetString("msgSolarSystemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUTH|As the south as in compass point.
        /// </summary>
        internal static string msgSouth {
            get {
                return ResourceManager.GetString("msgSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast|southeast as long text.
        /// </summary>
        internal static string msgSouthEastLong {
            get {
                return ResourceManager.GetString("msgSouthEastLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE|South-East upper case.
        /// </summary>
        internal static string msgSouthEastShortUpper {
            get {
                return ResourceManager.GetString("msgSouthEastShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south|south as long text.
        /// </summary>
        internal static string msgSouthLong {
            get {
                return ResourceManager.GetString("msgSouthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S|South upper case.
        /// </summary>
        internal static string msgSouthShortUpper {
            get {
                return ResourceManager.GetString("msgSouthShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast|southwest as long text.
        /// </summary>
        internal static string msgSouthWestLong {
            get {
                return ResourceManager.GetString("msgSouthWestLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW|South-West upper case.
        /// </summary>
        internal static string msgSouthWestShortUpper {
            get {
                return ResourceManager.GetString("msgSouthWestShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidereal time: {0:F2} h.|As in sidereal time.
        /// </summary>
        internal static string msgStarTime {
            get {
                return ResourceManager.GetString("msgStarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped|As in stopped.
        /// </summary>
        internal static string msgStopped {
            get {
                return ResourceManager.GetString("msgStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun is not visible|Sun is not visible.
        /// </summary>
        internal static string msgSunNotVisible {
            get {
                return ResourceManager.GetString("msgSunNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time|As in time.
        /// </summary>
        internal static string msgTime {
            get {
                return ResourceManager.GetString("msgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to east|As in to the east.
        /// </summary>
        internal static string msgToEast {
            get {
                return ResourceManager.GetString("msgToEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to north|As in to the north.
        /// </summary>
        internal static string msgToNorth {
            get {
                return ResourceManager.GetString("msgToNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to northeast|As in to the northeast.
        /// </summary>
        internal static string msgToNorthEast {
            get {
                return ResourceManager.GetString("msgToNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to northwest|As in to the northwest.
        /// </summary>
        internal static string msgToNorthWest {
            get {
                return ResourceManager.GetString("msgToNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to south|As in to the south.
        /// </summary>
        internal static string msgToSouth {
            get {
                return ResourceManager.GetString("msgToSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to southeast|As in to the southeast.
        /// </summary>
        internal static string msgToSouthEast {
            get {
                return ResourceManager.GetString("msgToSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to southwest|As in to the southwest.
        /// </summary>
        internal static string msgToSouthWest {
            get {
                return ResourceManager.GetString("msgToSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to west|As in to the west.
        /// </summary>
        internal static string msgToWest {
            get {
                return ResourceManager.GetString("msgToWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper case letter|As in upper case letter/character.
        /// </summary>
        internal static string msgUpperLetter {
            get {
                return ResourceManager.GetString("msgUpperLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC|As Univeral Coordinated Time.
        /// </summary>
        internal static string msgUTC {
            get {
                return ResourceManager.GetString("msgUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEST|As the west as in compass point.
        /// </summary>
        internal static string msgWest {
            get {
                return ResourceManager.GetString("msgWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west|west as long text.
        /// </summary>
        internal static string msgWestLong {
            get {
                return ResourceManager.GetString("msgWestLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W|West upper case.
        /// </summary>
        internal static string msgWestShortUpper {
            get {
                return ResourceManager.GetString("msgWestShortUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole solar system|Zoom so the whole solar system is visible.
        /// </summary>
        internal static string msgWholeSolSys {
            get {
                return ResourceManager.GetString("msgWholeSolSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR              : Harvard Revised Number = Bright Star Number;Name            : Name, generally Bayer and/or Flamsteed name;DM              : Durchmusterung Identification;HD              : Henry Draper Catalog Number;SAO             : SAO Catalog Number;FK5             : FK5-number;IRflag          : I if infrared source;RAh1900         : RA, hours / B1900;RAh1900         : RA, minutes / B1900;RAh1900         : RA, seconds / B1900;DE-1900         : Declination, sign / B1900;DEd1900         : Declination, de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msgYaleItems {
            get {
                return ResourceManager.GetString("msgYaleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year|As in year of time.
        /// </summary>
        internal static string msgYear {
            get {
                return ResourceManager.GetString("msgYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years|In a combo box selection list.
        /// </summary>
        internal static string msgYears {
            get {
                return ResourceManager.GetString("msgYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years|amount of years.
        /// </summary>
        internal static string msgYearsAmount {
            get {
                return ResourceManager.GetString("msgYearsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %|As in zoom in n %.
        /// </summary>
        internal static string msgZoomPercentage {
            get {
                return ResourceManager.GetString("msgZoomPercentage", resourceCulture);
            }
        }
    }
}
