//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StarMap_MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StarMap_MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMap.StarMap.MainForm", typeof(StarMap_MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Apu_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Apu.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apu.
        /// </summary>
        internal static string Apu_Name {
            get {
                return ResourceManager.GetString("Apu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes ApuValikko_Modifiers {
            get {
                object obj = ResourceManager.GetObject("ApuValikko.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApuValikko.
        /// </summary>
        internal static string ApuValikko_Name {
            get {
                return ResourceManager.GetString("ApuValikko.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Asetukset_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Asetukset.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        internal static string Asetukset_Name {
            get {
                return ResourceManager.GetString("Asetukset.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes AurinkoK_Modifiers {
            get {
                object obj = ResourceManager.GetObject("AurinkoK.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AurinkoK.
        /// </summary>
        internal static string AurinkoK_Name {
            get {
                return ResourceManager.GetString("AurinkoK.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes BrowseDb_Modifiers {
            get {
                object obj = ResourceManager.GetObject("BrowseDb.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrowseDb.
        /// </summary>
        internal static string BrowseDb_Name {
            get {
                return ResourceManager.GetString("BrowseDb.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comstellations {
            get {
                object obj = ResourceManager.GetObject("comstellations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool East_Locked {
            get {
                object obj = ResourceManager.GetObject("East.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes East_Modifiers {
            get {
                object obj = ResourceManager.GetObject("East.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string East_Name {
            get {
                return ResourceManager.GetString("East.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_app {
            get {
                object obj = ResourceManager.GetObject("exit_app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_char {
            get {
                object obj = ResourceManager.GetObject("help_char", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Hyppää_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Hyppää.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyppää.
        /// </summary>
        internal static string Hyppää_Name {
            get {
                return ResourceManager.GetString("Hyppää.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=108,Y=17}.
        /// </summary>
        internal static System.Drawing.Point imageList1_Location {
            get {
                object obj = ResourceManager.GetObject("imageList1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes imageList1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("imageList1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imageList1.
        /// </summary>
        internal static string imageList1_Name {
            get {
                return ResourceManager.GetString("imageList1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jump {
            get {
                object obj = ResourceManager.GetObject("jump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes KompassiShow_Modifiers {
            get {
                object obj = ResourceManager.GetObject("KompassiShow.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KompassiShow.
        /// </summary>
        internal static string KompassiShow_Name {
            get {
                return ResourceManager.GetString("KompassiShow.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes KopioLeikepöydälle_Modifiers {
            get {
                object obj = ResourceManager.GetObject("KopioLeikepöydälle.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KopioLeikepöydälle.
        /// </summary>
        internal static string KopioLeikepöydälle_Name {
            get {
                return ResourceManager.GetString("KopioLeikepöydälle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Lopeta_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Lopeta.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopeta.
        /// </summary>
        internal static string Lopeta_Name {
            get {
                return ResourceManager.GetString("Lopeta.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=56}.
        /// </summary>
        internal static System.Drawing.Point mainMenu1_Location {
            get {
                object obj = ResourceManager.GetObject("mainMenu1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes mainMenu1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("mainMenu1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainMenu1.
        /// </summary>
        internal static string mainMenu1_Name {
            get {
                return ResourceManager.GetString("mainMenu1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes menuItem1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem1.
        /// </summary>
        internal static string menuItem1_Name {
            get {
                return ResourceManager.GetString("menuItem1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes menuItem2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem2.
        /// </summary>
        internal static string menuItem2_Name {
            get {
                return ResourceManager.GetString("menuItem2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes menuItem3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem3.
        /// </summary>
        internal static string menuItem3_Name {
            get {
                return ResourceManager.GetString("menuItem3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes menuItem4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("menuItem4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem4.
        /// </summary>
        internal static string menuItem4_Name {
            get {
                return ResourceManager.GetString("menuItem4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes MerkkiSeli_Modifiers {
            get {
                object obj = ResourceManager.GetObject("MerkkiSeli.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MerkkiSeli.
        /// </summary>
        internal static string MerkkiSeli_Name {
            get {
                return ResourceManager.GetString("MerkkiSeli.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes NäytäRaDec_Modifiers {
            get {
                object obj = ResourceManager.GetObject("NäytäRaDec.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NäytäRaDec.
        /// </summary>
        internal static string NäytäRaDec_Name {
            get {
                return ResourceManager.GetString("NäytäRaDec.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool North_Locked {
            get {
                object obj = ResourceManager.GetObject("North.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes North_Modifiers {
            get {
                object obj = ResourceManager.GetObject("North.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string North_Name {
            get {
                return ResourceManager.GetString("North.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool pictureBox1_Locked {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes pictureBox1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pictureBox1.
        /// </summary>
        internal static string pictureBox1_Name {
            get {
                return ResourceManager.GetString("pictureBox1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes PlaneettaJaAJaK_Modifiers {
            get {
                object obj = ResourceManager.GetObject("PlaneettaJaAJaK.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaneettaJaAJaK.
        /// </summary>
        internal static string PlaneettaJaAJaK_Name {
            get {
                return ResourceManager.GetString("PlaneettaJaAJaK.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play0 {
            get {
                object obj = ResourceManager.GetObject("play0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play1 {
            get {
                object obj = ResourceManager.GetObject("play1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play2 {
            get {
                object obj = ResourceManager.GetObject("play2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sol_info {
            get {
                object obj = ResourceManager.GetObject("sol_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sol_sys {
            get {
                object obj = ResourceManager.GetObject("sol_sys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool South_Locked {
            get {
                object obj = ResourceManager.GetObject("South.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes South_Modifiers {
            get {
                object obj = ResourceManager.GetObject("South.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        internal static string South_Name {
            get {
                return ResourceManager.GetString("South.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stardb {
            get {
                object obj = ResourceManager.GetObject("stardb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool statusBar1_Locked {
            get {
                object obj = ResourceManager.GetObject("statusBar1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBar1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBar1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBar1.
        /// </summary>
        internal static string statusBar1_Name {
            get {
                return ResourceManager.GetString("statusBar1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel1.
        /// </summary>
        internal static string statusBarPanel1_Name {
            get {
                return ResourceManager.GetString("statusBarPanel1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel2.
        /// </summary>
        internal static string statusBarPanel2_Name {
            get {
                return ResourceManager.GetString("statusBarPanel2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel3.
        /// </summary>
        internal static string statusBarPanel3_Name {
            get {
                return ResourceManager.GetString("statusBarPanel3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel4.
        /// </summary>
        internal static string statusBarPanel4_Name {
            get {
                return ResourceManager.GetString("statusBarPanel4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel5_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel5.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel5.
        /// </summary>
        internal static string statusBarPanel5_Name {
            get {
                return ResourceManager.GetString("statusBarPanel5.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes statusBarPanel6_Modifiers {
            get {
                object obj = ResourceManager.GetObject("statusBarPanel6.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusBarPanel6.
        /// </summary>
        internal static string statusBarPanel6_Name {
            get {
                return ResourceManager.GetString("statusBarPanel6.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Tähtikuviot_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Tähtikuviot.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tähtikuviot.
        /// </summary>
        internal static string Tähtikuviot_Name {
            get {
                return ResourceManager.GetString("Tähtikuviot.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Tiedosto_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Tiedosto.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedosto.
        /// </summary>
        internal static string Tiedosto_Name {
            get {
                return ResourceManager.GetString("Tiedosto.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes Tietoja_Modifiers {
            get {
                object obj = ResourceManager.GetObject("Tietoja.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja.
        /// </summary>
        internal static string Tietoja_Name {
            get {
                return ResourceManager.GetString("Tietoja.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point timer1_Location {
            get {
                object obj = ResourceManager.GetObject("timer1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes timer1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("timer1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer1.
        /// </summary>
        internal static string timer1_Name {
            get {
                return ResourceManager.GetString("timer1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool toolBar1_Locked {
            get {
                object obj = ResourceManager.GetObject("toolBar1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBar1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBar1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolBar1.
        /// </summary>
        internal static string toolBar1_Name {
            get {
                return ResourceManager.GetString("toolBar1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton2_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton2.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolBarButton2.
        /// </summary>
        internal static string toolBarButton2_Name {
            get {
                return ResourceManager.GetString("toolBarButton2.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton3_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton3.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolBarButton3.
        /// </summary>
        internal static string toolBarButton3_Name {
            get {
                return ResourceManager.GetString("toolBarButton3.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes toolBarButton4_Modifiers {
            get {
                object obj = ResourceManager.GetObject("toolBarButton4.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolBarButton4.
        /// </summary>
        internal static string toolBarButton4_Name {
            get {
                return ResourceManager.GetString("toolBarButton4.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool West_Locked {
            get {
                object obj = ResourceManager.GetObject("West.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        internal static System.CodeDom.MemberAttributes West_Modifiers {
            get {
                object obj = ResourceManager.GetObject("West.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string West_Name {
            get {
                return ResourceManager.GetString("West.Name", resourceCulture);
            }
        }
    }
}
