CREATE TABLE WORLDCITIES( 
ID INTEGER PRIMARY KEY AUTOINCREMENT,
ISO3166_1_COUNTRYCODE TEXT, 
FIPS_5_2_SUBDIVISIONCODE TEXT, 
GNS_FD TEXT,
GNS_UFI INTEGER,
ISO_639_1_LANGUAGECODE TEXT, 
LANGUAGESCRIPT TEXT, 
NAME TEXT, 
LATITUDE REAL, 
LONGITUDE REAL, 
RTL INTEGER);

CREATE TABLE LICENSE(
LICENSETEXT TEXT NOT NULL);

CREATE INDEX NLATLON ON WORLDCITIES(NAME, LATITUDE, LONGITUDE);
